name: "Docker"

on:
  # Always have a base image ready to go - this is a nightly build
  schedule:
    - cron: 0 3 * * *

  # Allow manual trigger of a build
  workflow_dispatch:

  # On push to main we build and deploy images
  push:
    branches:
      - master

  # Publish packages on release
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
      - name: Run Actions Cleaner
        uses: easimon/maximize-build-space@v8
        with:
          overprovision-lvm: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v4

      # It's easier to reference named variables than indexes of the matrix
      - name: pull docker
        run: docker pull ghcr.io/mfem/containers/developer-cpu:latest
        working-directory:  ${{github.workspace}}

      - name: pull docker
        run: docker run --cap-add=SYS_PTRACE -p 3000:3000 -p 8000:8000 -p 8080:8080 ghcr.io/mfem/containers/developer-cpu:latest
        working-directory:  ${{github.workspace}}
            
      - name: Config MFEMMGIS
        run: cmake -B ${{github.workspace}}/build

      - name: Build MFEMMGIS
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Ctest
        working-directory: ${{github.workspace}}/build
        run: make examples && ctest -C --rerun-failed --output-on-failure ${{env.BUILD_TYPE}}
