name: "Docker"

on:
  # Always have a base image ready to go - this is a nightly build
  schedule:
    - cron: 0 3 * * *

  # Allow manual trigger of a build
  workflow_dispatch:

  # On push to main we build and deploy images
  push:
    branches:
      - master

  # Publish packages on release
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mfem/containers/developer-cpu:latest

    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: test
        run: echo "$LD_LIBRARY_PATH"
            
#      - name: Config MFEMMGIS
#        run: cmake -B ${{github.workspace}}/build

#      - name: Build MFEMMGIS
#        # Build your program with the given configuration
#        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

#      - name: Ctest
#        working-directory: ${{github.workspace}}/build
#        run: make examples && ctest -C --rerun-failed --output-on-failure ${{env.BUILD_TYPE}}
